name: Build & release
on:
  push:
    branches:
      - main
    paths:
      - "**/*.cpp"
      - "**/*.c"
      - "**/*.h"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: gcc eng.c -o dist/english.exe && g++ esp.cpp -o dist/spanish.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: dist/
  
  release:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with: 
          name: windows
          path: dist/
      - name: Package Windows build
        run: tar -czf windows.tgz dist 
      - name: Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          name: From commit ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          tag: ${{ github.repository }}@${{ github.sha }}
          artifacts: ./windows.tgz


