name: Build & release
on:
  push:
    branches:
      - main
    paths:
      - "**/*.cpp"
      - "**/*.c"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));
          refreshenv;
      - name: Install MinGW
        run: choco install mingw -y
      - name: Build
        run: gcc eng.c -o dist/english.exe && g++ esp.cpp -o dist/spanish.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: dist/
  build-linux:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install gcc
        run: sudo apt update && sudo apt install gcc 
      - name: Build
        run: gcc eng.c -o dist/english.exe && g++ esp.cpp -o dist/spanish.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: dist/
  release:
    needs: 
      - build-windows
      - build-linux 
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows build
        uses: actions/download-artifact@v3
        with: 
          name: windows
          path: windows/dist/
      - name: Download Linux build
        uses: actions/download-artifact@v3
        with: 
          name: linux
          path: linux/dist/
      - name: Package Windows build
        run: tar -czf windows.tgz windows/dist 
      - name: Package Linux build
        run: tar -czf linux.tgz linux/dist 
      - name: Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          tag: ${{ github.sha }}
          name: From commit ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          artifacts: ./*.tgz


